BankSystem_Statusbank_sinyaeva/urls.py
from django.contrib import admin
from django.urls import path, include
from automated_system_statusbank.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('statusbanksystem/', include('automated_system_statusbank.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

automated_system_statusbank/urls.py
from django.urls import path
from . import views

app_name = 'automatedsystemstatusbank'
urlpatterns = [
    path('home/', views.home, name='home'),

    path('clients/', views.clients, name='clients'),
    path('clients/<int:client_id>/', views.client_details, name='client_details'),

    path('clients/<int:address_id>/edit/address/', views.edit_address, name='edit_client_address'),
    path('clients/<int:client_id>/edit/passport/', views.edit_passport, name='edit_client_passport'),
    path('clients/<int:client_id>/edit/personal/', views.edit_personal, name='edit_client_personal'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='delete_client'),

    path('clients/add/', views.addclient, name='add_client'),

    path('deposits/', views.deposits, name='deposits'),
    path('deposits/<int:deposit_id>/', views.deposit_details, name='deposit_details'),
    path('deposits/<int:deposit_id>/edit/', views.edit_deposit, name='edit_deposit'),
    path('deposits/add', views.add_deposit, name='add_deposit'),
    path('deposits/<int:deposit_id>/delete/', views.delete_deposit, name='delete_deposit'),

]

templates/deposits/deposit_details.html
{% extends 'base.html' %}

{% block title %}Информация о вкладе{% endblock %}

{% block content %}


<div class="rounded" style="margin-top: 5%; margin-left: 5%; margin-right: 5%; margin-bottom: 5%; background-color: rgb(33,37,41); color: #e1e1e1">

    <hr>
    <div style="margin-top: 30px; margin-bottom: 70px; text-align: center">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
        <legend>Вклад клиента {{ deposit.client }}</legend>
    </div>
    <hr>

    <div style="text-align: left">
        <div class="row" style="margin-left: 10%">
            <div class="col">
                <h4 style="margin-top: 10px">Номер договора</h4>
                {{ deposit.contract_number }}
                <h4 style="margin-top: 10px">Тип депозита</h4>
                {{ deposit.deposit_type }}
                <h4 style="margin-top: 10px">Сумма депозита и валюта</h4>
                {{ deposit.deposit_sum }} {{ deposit.currency }}
                <h4 style="margin-top: 10px">Процент</h4>
                {{ deposit.percentage }}
                <h4 style="margin-top: 10px">Дата заключения договора</h4>
                {{ deposit.date_of_issue }}
                <h4 style="margin-top: 10px">Срок действия</h4>
                {{ deposit.date_of_expire }}
                <h4 style="margin-top: 10px">Активен</h4>
                {% if deposit.is_active %}
                    Да
                {% else %}
                    Нет
                {% endif %}
            </div>
            <div class="col">
                <h4 style="margin-top: 10px">Клиент</h4>
                {{ deposit.client }}
                <h4 style="margin-top: 10px">Работник</h4>
                {{ deposit.worker.last_name }} {{ deposit.worker.first_name }}
            </div>
        </div>
        <div class="container" style="text-align: center">
            <a class="btn btn-outline-success" href="{% url 'automatedsystemstatusbank:edit_deposit' deposit.id %}">Редактировать</a>
        </div>
    </div>
    <hr>
        <div class="container" style="text-align: center">
            <a class="btn btn-danger" href="{% url 'automatedsystemstatusbank:delete_deposit' deposit.id %}">Удалить вклад</a>
        </div>
    <hr>
</div>

{% endblock %}

templates/deposits/deposit_new.html
{% extends 'base.html' %}

{% block title %}Информация о депозите{% endblock %}

{% block content %}

<div class="rounded" style="margin-top: 5%; margin-left: 5%; margin-right: 5%; margin-bottom: 5%; background-color: rgb(33,37,41); color: #e1e1e1">
    <hr>
    {% if edit %}
        <h4 style="text-align: center; margin-bottom: 3%">Редактирование депозита</h4>
    {% else %}
        <h4 style="text-align: center; margin-bottom: 3%">Добавление нового депозита</h4>
    {% endif %}
    <form method="POST" class="post-form">
    {% csrf_token %}
<hr>
            <div style="margin-top: 30px; margin-bottom: 5%; text-align: center">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                    <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                    <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                    <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
                </svg>
                {% if edit %}
                <legend>Редактировать депозит</legend>
                {% else %}
                <legend>Новый депозит</legend>
                {% endif %}
            </div>
            <div style="text-align: left; margin-left: 5%; margin-bottom: 5%">
                {{ form.as_p }}
            </div>
    <hr>
        <div class="container" style="text-align: center">
            <button type="submit" style="margin-bottom: 50px" class="btn btn-success">Сохранить</button>
    </div>
    </form>
</div>

{% endblock %}

templates/deposits/deposits.html
{% extends 'base.html' %}

{% block title %}Депозиты{% endblock %}

{% block content %}


{% if deposits %}
    <h4 style="text-align: center; margin-top: 5%; margin-bottom: 3%">База депозитов Статусбанка</h4>
    <table class="table table-hover table-dark" style="margin-bottom: 10%">
    <caption>ОАО «СтатусБанк»</caption>
  <thead>
    <tr>
      <th scope="col">№</th>
      <th scope="col">ФИО вкладчика</th>
      <th scope="col">Тип вклада</th>
      <th scope="col">Сумма</th>
      <th scope="col">Процент</th>
      <th scope="col"><a class="btn btn-outline-success" href="{% url 'automatedsystemstatusbank:add_deposit' %}">Новый</a></th>
    </tr>
  </thead>
  <tbody>
    {% for deposit in deposits %}
    <tr>
      <th scope="row">{{ deposit.id }}</th>
      <td>{{ deposit.client }}</td>
      <td>{{ deposit.deposit_type }}</td>
      <td>{{ deposit.deposit_sum }} {{ deposit.currency }}</td>
      <td>{{ deposit.percentage }}</td>
      <td><a class="btn btn-outline-info" style="alignment: left" href="{% url 'automatedsystemstatusbank:deposit_details' deposit.id %}">Перейти</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% else %}
    <div class="container" style="text-align: center; margin-top: 20%">
        <h4>Нет депозитов</h4>
        <a style="text-align: center" class="btn btn-primary" href="{% url 'automatedsystemstatusbank:add_deposit' %}">Создать новый</a>
    </div>{% endif %}

{% endblock %}