BankSystem_Statusbank_sinyaeva/urls.py
from django.contrib import admin
from django.urls import path, include
from automated_system_statusbank.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('statusbanksystem/', include('automated_system_statusbank.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

automated_system_statusbank/urls.py
from django.urls import path
from . import views

app_name = 'automatedsystemstatusbank'
urlpatterns = [
    path('home/', views.home, name='home'),

    path('clients/', views.clients, name='clients'),
    path('clients/<int:client_id>/', views.client_details, name='client_details'),

    path('clients/<int:address_id>/edit/address/', views.edit_address, name='edit_client_address'),
    path('clients/<int:client_id>/edit/passport/', views.edit_passport, name='edit_client_passport'),
    path('clients/<int:client_id>/edit/personal/', views.edit_personal, name='edit_client_personal'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='delete_client'),

    path('clients/add/', views.addclient, name='add_client'),

    path('deposits/', views.deposits, name='deposits'),
    path('deposits/<int:deposit_id>/', views.deposit_details, name='deposit_details'),
    path('deposits/<int:deposit_id>/edit/', views.edit_deposit, name='edit_deposit'),
    path('deposits/add', views.add_deposit, name='add_deposit'),
    path('deposits/<int:deposit_id>/delete/', views.delete_deposit, name='delete_deposit'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background: {% block bgcolor %}{% endblock %}">

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'automatedsystemstatusbank:home' %}">
          <img alt="logo" src="https://stbank.by/local/templates/stbank_by/img/content/logo2-20years_240%D1%8538.svg" width="150" height="30" loading="lazy">
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active"
             aria-current="page"
             href="{% url 'automatedsystemstatusbank:home' %}">Главная</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#"
             id="navbarDropdown"
             role="button"
             data-bs-toggle="dropdown"
             aria-expanded="false">
            Клиенты
          </a>
          <ul class="dropdown-menu"
              aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item"
            href="{% url 'automatedsystemstatusbank:clients' %}">Просмотреть клиентов</a></li>
            <li><a class="dropdown-item"
            href="{% url 'automatedsystemstatusbank:add_client' %}">Добавить клиента</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#"
             id="navbarDropdown"
             role="button"
             data-bs-toggle="dropdown"
             aria-expanded="false">
            Депозиты
          </a>
          <ul class="dropdown-menu"
              aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item"
            href="{% url 'automatedsystemstatusbank:deposits' %}">Просмотреть депозиты</a></li>
            <li><a class="dropdown-item"
            href="{% url 'automatedsystemstatusbank:add_deposit' %}">Добавить депозит</a></li>
          </ul>
        </li>
        <li class="nav-item" role="presentation">
            <a class="btn btn-outline-danger" id="contact-tab" data-toggle="tab" href="{% url 'logout' %}" role="tab" aria-controls="credits" aria-selected="false">Выйти из системы</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}

   <div class="container" style="background-color: whitesmoke; margin-top: 10%;">
	<h1 class="loans-main__title">О Банке | СтатусБанк – надежный финансовый партнер на долгие годы</h1>
	<div class="speach">
		ОАО «СтатусБанк» - один из самых динамично развивающихся банков Республики Беларусь,
        который целенаправленно осваивает современные банковские технологии, обладает устойчивой
        ресурсной базой и способен оперативно решать ваши самые насущные финансовые вопросы.
        Мы благодарим Вас за доверие и надеемся на успешное, плодотворное и взаимовыгодное сотрудничество.
        Мы работаем для того, чтобы ОАО «СтатусБанк» стал для вас надежным, удобным и умным финансовым партнером
        на долгие годы.
    </div>
</div>

    <div class="container"><br></div>

<div class="container" style="background-color: whitesmoke; margin-bottom: 10%">
    <h2>НАША МИССИЯ</h2>
<br>
    <div>
        Удовлетворение потребностей наших клиентов в современных, доступных и качественных банковских услугах,
        содействие успеху в достижении целей и предоставление широкого спектра финансовых инструментов предприятиям
        всех форм собственности на базе клиентоориентированной, высокоэффективной, динамично развивающейся
        бизнес-модели, современных информационных технологий и высоких стандартов обслуживания.
    </div>
<div>
 <br>
</div>
<div>
 <br>
</div> <h2>ИСТОРИЯ БАНКА</h2>
 <br>
<p>
    ОАО «СтатусБанк» (ОАО «Международный резервный банк» – с 25.02.2002 по 20.01.2013, ОАО «Евроторгинвестбанк» – с
    21.01.2013 по 25.05.2017) (г. Минск) создано в 2002 году для обслуживания корпоративных клиентов-резидентов
    свободной экономической зоны «Минск» и нерезидентов Республики Беларусь, - а также частных клиентов-нерезидентов
    Республики Беларусь. За время работы на белорусском рынке Банк приобрел имидж надежного делового партнера, который
    оказывает своим клиентам финансовые услуги на самом высоком уровне, оперативно реагирует на все изменения
    банковского рынка и постоянно совершенствует и расширяет спектр предлагаемых продуктов. В конце 2007 года была
    разработана и принята новая стратегия развития, которая предусматривала поэтапный переход Банка в разряд универсальных.
</p>
<p>
	 Сегодня, продолжая работать в направлении обслуживания юридических лиц и индивидуальных предпринимателей,
    Банк активно развивает розничный бизнес, делая акцент на широкой линейке кредитных продуктов, разнообразных
    инструментах выдачи кредитов, развитии сети отделений и точек продаж.
</p>
<p>
	 Кадровая политика ОАО "СтатусБанк" направлена на формирование команды профессионалов, способных быстро и
    качественно решать стоящие перед банком задачи.
</p>
<p>
	 25 мая 2017 года Банк переименован в ОАО «СтатусБанк».
</p>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Приветствуем!{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}

    <div class="rounded" style="text-align: center;margin-left: 10%; margin-right: 10%; background-color: rgb(33,37,41); color: #e1e1e1">
        <hr>
        <div class="row" style="text-align: center">
            <div class="col">
                <div class="card text-white bg-dark" style="width: 50%; text-align: center; margin-left: 25%">
                    <img src="https://stbank.by/upload/medialibrary/stbank.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title">Добро пожаловать!</h3>
                        <h5 class="card-subtitle mb-5 mt-5">Автоматизированная информационная система разработана с целью
                                                    сокращения затрат времени на обслуживание клиентов отдела
                                                    розничного бизнеса банка ОАО «СтатусБанк»
                        </h5>
                        <p class="card-text">Для начала работы, пожалуйста, авторизуйтесь</p>
                    </div>
                    <div class="card-body">
                        <a href="accounts/login" class="btn btn-success">Авторизация</a>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>

{% endblock %}